### ISSUE TITLE
P2P Code Review

### ISSUE THREAD

**Issue by damdafayton** [mirouhml/leaderboard#4]
https://github.com/mirouhml/leaderboard/blob/fa22058b3defbe524ae30776d5fddd8bf65bb0ba/src/modules/leaderboard.js#L10

- It would make code cleaner to declare this as `const` within the function which uses this query.

- Also the class containing this constructor can extend the class which it's creating a new instance currently.

**Comment by mirouhml** [comment]
Thanks for the review!

**Comment by mirouhml** [comment]
I've implemented this, thanks again!
